services:
  go:
    image: golang:1.22.3
    container_name: go-argparse-go
    volumes:
      - ./:/app
    working_dir: /app

networks:
  default:
    driver: bridge
    name: go-argparse-local-net

